title: "AFDP '2020"
name:  "AFDP '2020"
description: "International Workshop on Agile and Functional Data Pipelines"
exclude:
  - ".gitignore"
  - ".jekyll-cache"
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
image:
  path: /assets/favicon.png
